version: '3'
services:
  news_api:
    build: news/src/
    ports:
      - "1001:8000"
    environment:
        - NEWS_API_1=${NEWS_API_1}
        - NEWS_API_2=${NEWS_API_2}
        - NEWS_API_3=${NEWS_API_3}
        - NEWS_API_4=${NEWS_API_4}
    container_name: news_api
    volumes:
      - ./news/src:/app
  coins_api:
    build: coins/src/
    ports:
      - "1002:8000"
    container_name: coins_api
    volumes:
      - ./coins/src:/app