version: '3'
services:
  api_gateway:
    build: src/
    ports:
      - "2000:8000"
    environment:
        - NEWS_API_PRIVATE_CONTAINER_URL=${NEWS_API_PRIVATE_CONTAINER_URL}
        - COINS_API_PRIVATE_CONTAINER_URL=${COINS_API_PRIVATE_CONTAINER_URL}
    container_name: api_gateway
    volumes:
      - ./src:/app
    